appName: techtrends
namespace: prod

replicaCount: 5

image:
  repository: lebaotoan/techtrends
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

ports:
  name: app-port
  containerPort: 3111
  protocol: TCP

livenessProbe:
  path: /healthz
  port: 3111

readinessProbe:
  path: /healthz
  port: 3111

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 350m
    memory: 128Mi


service:
  type: ClusterIP
  port: 7111
  targetPort: 3111
  protocol: TCP